ECommerceSite/Models/Cart.cs
namespace ECommerceSite.Models
{
    public class Cart
    {
        public int CartId { get; set; }
        public int CustomerId { get; set; }
        public int Quantity { get; set; }

        public IList<CartItem> Items { get; set; } = new List<CartItem>();
    }
}

ECommerceSite/Models/Category.cs
using System;
using System.Collections.Generic;

namespace ECommerceSite.Models
{
    public partial class Category
    {
        public Category()
        {
            Products = new HashSet<Product>();
        }

        public int CategoryId { get; set; }
        public string CategoryName { get; set; } = null!;
        public string? Description { get; set; }
        public byte[]? Picture { get; set; }

        public virtual ICollection<Product> Products { get; set; }
    }
}

ECommerceSite/Models/Product.cs
using System;
using System.Collections.Generic;

namespace ECommerceSite.Models
{
    public partial class Product
    {
        public Product()
        {
            OrderDetails = new HashSet<OrderDetail>();
        }

        public int ProductId { get; set; }
        public string ProductName { get; set; } = null!;
        public int? SupplierId { get; set; }
        public int CategoryId { get; set; }
        public string? QuantityPerUnit { get; set; }
        public decimal UnitPrice { get; set; }
        public short? UnitsInStock { get; set; }
        public short? UnitsOnOrder { get; set; }
        public short? ReorderLevel { get; set; }
        public bool Discontinued { get; set; }

        public virtual Category? Category { get; set; }
        public virtual Supplier? Supplier { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}

ECommerceSite/Pages/Cart.cshtml.cs
using Bogus.DataSets;
using ECommerceSite.Models;
using ECommerceSite.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Build.Framework;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using RequiredAttribute = System.ComponentModel.DataAnnotations.RequiredAttribute;

namespace ECommerceSite.Pages
{
    [BindProperties]
    public class CartModel : PageModel
    {
        private readonly ICartService _cartService;
        private readonly ECommerceDBContext _dBContext;

        public CartModel(ICartService cartService, ECommerceDBContext dBContext)
        {
            _cartService = cartService;
            _dBContext = dBContext;
        }
        public int Id { get; set; }
        public decimal TotalPrice { get; set; }
        public int CustomerId { get; set; }
        [Required]
        [MaxLength(100)]
        public string FirstName { get; set; }
        [Required]
        [MaxLength(100)]
        public string LastName { get; set; }
        [Required]
        [MaxLength(200)]
        [EmailAddress(ErrorMessage ="Please enter a valid email adress")]
        public string Email { get; set; }
        [Required]
        public string Address { get; set; }
        [Required]
        [StringLength(50)]
        public string City { get; set; }
        [Required]
        [StringLength(50)]
        public string Country { get; set; }
        [Required]
        public int ZipCode { get; set; }
        [Required]
        public int PhoneNumber { get; set; }
 
        public void OnGet()
        {
            TotalPrice = _cartService.ShoppingCart.Sum(t => t.UnitPrice);
        }

        public IActionResult OnPost()
        {
            var customer = new ShopCustomer();
            customer.FirstName = FirstName;
            customer.LastName = LastName;
            customer.Country = Country;
            customer.ZipCode = ZipCode;
            customer.PhoneNumber = PhoneNumber;
            customer.Email = Email;
            customer.Address = Address;
            customer.City = City;
            customer.Id = CustomerId;

            return RedirectToAction("Confirmation");
        }

        public void OnPostClearShoppingCart()
        {
            _cartService.ShoppingCart.Clear();
        }
    }
}

ECommerceSite/Pages/Category.cshtml.cs
using ECommerceSite.Models;
using ECommerceSite.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace ECommerceSite.Pages
{
    public class CategoryModel : PageModel
    {
        private readonly ECommerceDBContext _dbContext;
        private readonly IPageService _pageService;
        private readonly ICartService _cartService;
        private readonly IWishListService _wishListService;

        public CategoryModel(ECommerceDBContext dbContext, IPageService pageService, ICartService cartService, IWishListService wishListService)
        {
            _dbContext = dbContext;
            _pageService = pageService;
            _cartService = cartService;
            _wishListService = wishListService;
        }

        
        public string CategoryName { get; set; }
        public int CurrentPage { get; set; }
        public string Query { get; set; }
        public int PageCount { get; set; }
        public int ProductId { get; set; }
        public int Quantity { get; set; }
        public int CartId { get; set; }
        public int CategoryId { get; set; }


        public class CategoryViewModel
        {
            public int Id { get; set; }

            public string Name { get; set; }
        }

        public class ProductViewModel
        {
            public int Id { get; set; }

            public string Name { get; set; }

            public string CategoryName { get; set; }
            public int ProductId { get; set; }
            public int Quantity { get; set; }
            public int CartId { get; set; }

            public decimal UnitPrice { get; set; }
        }



        public List<CategoryViewModel> Categories { get; set; }
        public List<ProductViewModel> Products { get; set; }
        public void OnGet(string query, int id, int pageno = 1)
        {
            //Categories = _dbContext.Categories.Select(c => new CategoryViewModel
            //{
            //    Id = c.CategoryId,
            //    Name = c.CategoryName

            //}).ToList();


            CategoryName = _dbContext.Categories.First(r => r.CategoryId == id).CategoryName;
            CurrentPage = pageno;
            Query = query;
            Quantity = 1;
            CategoryId = id;

            var pageresult = _pageService.GetPages(CurrentPage, query);

            Products = _dbContext.Products
                .Include(e => e.Category)
                .OrderByDescending(t => t.ProductId)
                .Where(r => r.Category.CategoryId == id)
                .Select(r => new ProductViewModel
                {
                    Id = r.ProductId,
                    Name = r.ProductName,
                    CategoryName = r.Category.CategoryName,
                    UnitPrice = r.UnitPrice
                }).ToList();

            Categories = pageresult.Results.Select(x => new CategoryViewModel
            {
                Id = x.ProductId,
                Name = x.ProductName
            }).ToList();

            PageCount = pageresult.PageCount;

        }


        public IActionResult OnPostAddToCart(int productId, int categoryId)
        {
           var product = _dbContext.Products.FirstOrDefault(x => x.ProductId == productId);
            
            _cartService.ShoppingCart.Add(product);
            _wishListService.WishList.Remove(product);

            return RedirectToPage(new {Id = categoryId});

        }

        public IActionResult OnPostAddToWishList (int productId, int categoryId)
        {
            var product = _dbContext.Products.FirstOrDefault(x => x.ProductId == productId);

            _wishListService.WishList.Add(product);
            
            return RedirectToPage(new { Id = categoryId });
        }
    }
}

ECommerceSite/Pages/Checkout.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ECommerceSite.Pages
{
    public class CheckoutModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

ECommerceSite/Pages/Confirmation.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ECommerceSite.Pages
{
    public class ConfirmationModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

ECommerceSite/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace ECommerceSite.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

ECommerceSite/Pages/Index.cshtml.cs
using ECommerceSite.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ECommerceSite.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly ECommerceDBContext _dbContext;

        public IndexModel(ILogger<IndexModel> logger, ECommerceDBContext dbContext)
        {
            _logger = logger;
            _dbContext = dbContext;
        }

        public class CategoryViewModel
        {
            public int Id { get; set; }

            public string Name { get; set; }
        }

        public class ProductViewModel
        {
            public int Id { get; set; }

            public string Name { get; set; }

            public string CategoryName { get; set; }

            public decimal UnitPrice { get; set; }


        }

        public List<CategoryViewModel> Categories { get; set; }

        public List<ProductViewModel> Products { get; set; }

        public void OnGet()
        {
            Categories = _dbContext.Categories.Select(c => new CategoryViewModel
            {
                Id = c.CategoryId,
                Name = c.CategoryName

            }).ToList();

            Products = _dbContext.Products.Include(e => e.Category)
                .OrderByDescending(t => t.ProductId)
                .Take(5)
                .Select(r => new ProductViewModel
                {
                    Id = r.ProductId,
                    Name = r.ProductName,
                    CategoryName = r.Category.CategoryName,
                    UnitPrice = r.UnitPrice
                }).ToList();
        }
    }
    
}

ECommerceSite/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ECommerceSite.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

ECommerceSite/Pages/Product.cshtml.cs
using ECommerceSite.Models;
using ECommerceSite.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.CodeAnalysis;
using Microsoft.EntityFrameworkCore;

namespace ECommerceSite.Pages
{
    public class ProductModel : PageModel
    {
        private readonly ECommerceDBContext _dbContext;
        private readonly ICartService _cartService;
        private readonly IWishListService _wishListService;

        public ProductModel(ECommerceDBContext dbContext, ICartService cartService, IWishListService wishListService)
        {
            _dbContext = dbContext;
            _cartService = cartService;
            _wishListService = wishListService;
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public decimal UnitPrice { get; set; }
        public string CategoryName { get; set; }
        public int? CategoryId { get; set; }
        public int Quantity { get; set; }
        public int CartId { get; set; }




        public void OnGet(int id)
        {
            var product = _dbContext.Products.FirstOrDefault(x => x.ProductId == id);
            var category = _dbContext.Categories.FirstOrDefault(x => x.CategoryId == product.CategoryId);

            Id = product.ProductId;
            Name = product.ProductName;
            UnitPrice = product.UnitPrice;
            CategoryId = product.CategoryId;
            CategoryName = category.CategoryName;
            Quantity = 1;

        }

        public IActionResult OnPostAddToCart(int productId)
        {
            var product = _dbContext.Products.FirstOrDefault(x => x.ProductId == productId);

            _cartService.ShoppingCart.Add(product);

            return RedirectToPage(new { Id = productId });


        }

        public IActionResult OnPostAddToWishList(int productId)
        {
            var product = _dbContext.Products.FirstOrDefault(x => x.ProductId == productId);

            _wishListService.WishList.Add(product);

            return RedirectToPage(new { Id = productId });
        }
    }
}

ECommerceSite/Pages/SearchResult.cshtml.cs
using ECommerceSite.Models;
using ECommerceSite.Services;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace ECommerceSite.Pages
{
    public class SearchResultModel : PageModel
    {

        private readonly ECommerceDBContext _dbContext;
        private readonly ISearchService _searchServiceService;

        public SearchResultModel(ECommerceDBContext dbContext, ISearchService searchService)
        {
            _dbContext = dbContext;
            _searchServiceService = searchService;
        }

        public class ProductViewModel
        {
            public int Id { get; set; }

            public string Name { get; set; }

            public string CategoryName { get; set; }

            public decimal UnitPrice { get; set; }
        }

        public List<ProductViewModel> Products { get; set; }

        public void OnGet(string searchQuery)
        {
            var searchResult = _searchServiceService.SearchProduct(searchQuery);

            Products = _dbContext.Products
                .Include(e => e.Category)
                .OrderByDescending(t => t.ProductId)
                .Where(r => r.Category.CategoryName == searchQuery)
                .Select(r => new ProductViewModel
                {
                    Id = r.ProductId,
                    Name = r.ProductName,
                    CategoryName = r.Category.CategoryName,
                    UnitPrice = r.UnitPrice
                }).ToList();
        }
    }
}

ECommerceSite/Pages/Cart.cshtml
@page
@using ECommerceSite.Services
@model ECommerceSite.Pages.CartModel

@{
	@inject ICartService cartservice
}
<!-- BREADCRUMB -->
		<div id="breadcrumb" class="section">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
					<div class="col-md-12">
						<h3 class="breadcrumb-header">Checkout</h3>
						<ul class="breadcrumb-tree">
							<li><a href="#">Home</a></li>
							<li class="active">Checkout</li>
						</ul>
					</div>
				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
		<!-- /BREADCRUMB -->

		<!-- SECTION -->
		<div class="section">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">

					<div class="col-md-7">
						<!-- Billing Details -->
						<div class="billing-details">
							<div class="section-title">
								<h3 class="title">Billing address</h3>
							</div>
							<form method="post">
							<div class="form-group">
								
								<input class="input" type="text" name="first-name" asp-for="FirstName" placeholder="First Name">
								
							</div>
							<div class="form-group">
								<input class="input" type="text" name="last-name" asp-for="LastName" placeholder="Last Name">
							</div>
							<div class="form-group">
								<input class="input" type="email" name="email" asp-for="Email" placeholder="Email">
							</div>
							<div class="form-group">
								<input class="input" type="text" name="address" asp-for="Address" placeholder="Address">
							</div>
							<div class="form-group">
								<input class="input" type="text" name="city" asp-for="City" placeholder="City">
							</div>
							<div class="form-group">
								<input class="input" type="text" name="country" asp-for="Country" placeholder="Country">
							</div>
							<div class="form-group">
								<input class="input" type="text" name="zip-code" asp-for="ZipCode" placeholder="ZIP Code">
							</div>
							<div class="form-group">
								<input class="input" type="tel" name="tel" asp-for="PhoneNumber" placeholder="Telephone">
							</div>
							</form>
							<div class="form-group">
								<div class="input-checkbox">
									<input type="checkbox" id="create-account">
									<label for="create-account">
										<span></span>
										Create Account?
									</label>
									<div class="caption">
										<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt.</p>
										<input class="input" type="password" name="password" placeholder="Enter Your Password">
									</div>
								</div>
							</div>
						</div>
						<!-- /Billing Details -->

						<!-- Shiping Details -->
						<div class="shiping-details">
							<div class="section-title">
								<h3 class="title">Shiping address</h3>
							</div>
							<div class="input-checkbox">
								<input type="checkbox" id="shiping-address">
								<label for="shiping-address">
									<span></span>
									Ship to a diffrent address?
								</label>
								<div class="caption">
									<div class="form-group">
										<input class="input" type="text" name="first-name" placeholder="First Name">
									</div>
									<div class="form-group">
										<input class="input" type="text" name="last-name" placeholder="Last Name">
									</div>
									<div class="form-group">
										<input class="input" type="email" name="email" placeholder="Email">
									</div>
									<div class="form-group">
										<input class="input" type="text" name="address" placeholder="Address">
									</div>
									<div class="form-group">
										<input class="input" type="text" name="city" placeholder="City">
									</div>
									<div class="form-group">
										<input class="input" type="text" name="country" placeholder="Country">
									</div>
									<div class="form-group">
										<input class="input" type="text" name="zip-code" placeholder="ZIP Code">
									</div>
									<div class="form-group">
										<input class="input" type="tel" name="tel" placeholder="Telephone">
									</div>
								</div>
							</div>
						</div>
						<!-- /Shiping Details -->

						<!-- Order notes -->
						<div class="order-notes">
							<textarea class="input" placeholder="Order Notes"></textarea>
						</div>
						<!-- /Order notes -->
					</div>

					<!-- Order Details -->
					<div class="col-md-5 order-details">
						<div class="section-title text-center">
							<h3 class="title">Your Order</h3>
						</div>
						<div class="order-summary">
							<div class="order-col">
								<div><strong>PRODUCT</strong></div>
								<div><strong>TOTAL</strong></div>
							</div>
							<div class="order-products">
								@foreach(var product in cartservice.ShoppingCart)
								{
								<div class="order-col">
									<div>1x @product.ProductName</div>
									<div>@Math.Round(product.UnitPrice,2) EUR</div>
								</div>
						}
							<div class="order-col">
								<div>Shiping</div>
								<div><strong>FREE</strong></div>
							</div>
							<div class="order-col">
								<div><strong>TOTAL</strong></div>
							<div><strong class="order-total">@Math.Round(Model.TotalPrice, 2) EUR</strong></div>
							</div>
						</div>
						<div class="payment-method">
							<div class="input-radio">
								<input type="radio" name="payment" id="payment-1">
								<label for="payment-1">
									<span></span>
									Direct Bank Transfer
								</label>
								<div class="caption">
									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
								</div>
							</div>
							<div class="input-radio">
								<input type="radio" name="payment" id="payment-2">
								<label for="payment-2">
									<span></span>
									Cheque Payment
								</label>
								<div class="caption">
									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
								</div>
							</div>
							<div class="input-radio">
								<input type="radio" name="payment" id="payment-3">
								<label for="payment-3">
									<span></span>
									Paypal System
								</label>
								<div class="caption">
									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
								</div>
							</div>
						</div>
						<div class="input-checkbox">
							<input type="checkbox" id="terms">
							<label for="terms">
								<span></span>
								I've read and accept the <a href="#">terms & conditions</a>
							</label>
						</div>
						<form method="post" asp-page-handler="ClearShoppingCart">
						<a type="submit" asp-page="/Confirmation" class="primary-btn order-submit">Place order</a>
							</form>
					</div>
					<!-- /Order Details -->
				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
		<!-- /SECTION -->

		<!-- NEWSLETTER -->
		<div id="newsletter" class="section">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
					<div class="col-md-12">
						<div class="newsletter">
							<p>Sign Up for the <strong>NEWSLETTER</strong></p>
							<form>
								<input class="input" type="email" placeholder="Enter Your Email">
								<button class="newsletter-btn"><i class="fa fa-envelope"></i> Subscribe</button>
							</form>
							<ul class="newsletter-follow">
								<li>
									<a href="#"><i class="fa fa-facebook"></i></a>
								</li>
								<li>
									<a href="#"><i class="fa fa-twitter"></i></a>
								</li>
								<li>
									<a href="#"><i class="fa fa-instagram"></i></a>
								</li>
								<li>
									<a href="#"><i class="fa fa-pinterest"></i></a>
								</li>
							</ul>
						</div>
					</div>
				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
		<!-- /NEWSLETTER -->

ECommerceSite/Pages/Category.cshtml
@page
@model ECommerceSite.Pages.CategoryModel
@{
}

<!-- BREADCRUMB -->
		<div id="breadcrumb" class="section">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
					<div class="col-md-12">
						<ul class="breadcrumb-tree">
							<li><a asp-page="/Index">Home</a></li>
							<li class="active">@Model.CategoryName (@Model.Products.Count Results)</li>
						</ul>
					</div>
				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
<!-- /BREADCRUMB -->

		<!-- SECTION -->
		<div class="section">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
					<!-- ASIDE -->
					<div id="aside" class="col-md-3">
						<!-- aside Widget -->
						
						<div class="aside">
							@*<h3 class="aside-title">Categories</h3>*@
							
						@*		@foreach(var category in Model.Categories)
						{
							<div class="checkbox-filter">
								<div class="input-checkbox">
									<input type="checkbox" id="category-1">
									<label for="category-1">
										<span></span>
										<a asp-page="/Category" asp-route-id="@category.Id" class="cta-btn">@category.Name <i class="fa fa-arrow-circle-right"></i></a>
									</label>
								</div>


							</div>
						}*@
						</div>
						<!-- /aside Widget -->

						<!-- aside Widget -->
						<div class="aside">
							<h3 class="aside-title">Top selling</h3>
							@foreach(var products in Model.Products.Take(5))
							{

									<div class="product-widget">
										<div class="product-img">
											<img src="./img/product01.png" alt="">
										</div>
										<div class="product-body">
											<p class="product-category">@products.CategoryName</p>
											<a asp-page="/Product" asp-route-id="@products.Id" class="cta-btn"><h3 class="product-name">@products.Name</h3></a>
											<h4 class="product-price">@Math.Round(products.UnitPrice, 2)</h4>
										</div>
									</div>
							}
						</div>
						<!-- /aside Widget -->
					</div>
					<!-- /ASIDE -->

					<!-- STORE -->
					<div id="store" class="col-md-9">
						<!-- store top filter -->
						<div class="store-filter clearfix">
							<div class="store-sort">
								<label>
									Sort By:
									<select class="input-select">
										<option value="0">Popular</option>
										<option value="1">Position</option>
									</select>
								</label>

								<label>
									Show:
									<select class="input-select">
										<option value="0">20</option>
										<option value="1">50</option>
									</select>
								</label>
							</div>
							<ul class="store-grid">
								<li class="active"><i class="fa fa-th"></i></li>
								<li><a href="#"><i class="fa fa-th-list"></i></a></li>
							</ul>
						</div>
						<!-- /store top filter -->

						<!-- store products -->
						<div class="row">

							@foreach(var products in Model.Products)
							{
							<!-- product -->
							<div class="col-md-4 col-xs-6">
								<div class="product">
									<div class="product-img">
										<img src="./img/product01.png" alt="">
										<div class="product-label">
										</div>
									</div>
									<div class="product-body">
										<p class="product-category">@products.CategoryName</p>
										<h3 class="product-name"><a asp-page="/Product" asp-route-id="@products.Id" class="cta-btn">@products.Name</a></h3>
										<h4 class="product-price">@products.UnitPrice.ToString("0.00")</h4>
										<div class="product-rating">
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
										</div>
										<div class="product-btns">
										<form method="post" asp-page-handler="AddToWishList" asp-route-productId="@products.Id" asp-route-categoryId="@Model.CategoryId">
											<button class="add-to-wishlist"><i class="fa fa-heart-o"></i><span class="tooltipp">add to wishlist</span></button>
										</form>
										</div>
									</div>
									<div class="add-to-cart">
									<form method="post" asp-page-handler="AddToCart" asp-route-productId="@products.Id" asp-route-categoryId="@Model.CategoryId">
										<button class="add-to-cart-btn" ><i class="fa fa-shopping-cart"></i> add to cart</button>
									</form>
									</div>
								</div>
							</div>
							<!-- /product -->
							}

							
						</div>
						<!-- /store products -->

						<!-- store bottom filter -->
						<div class="store-filter clearfix">
							<span class="store-qty">Showing @Model.Products.Count() products</span>
					<!-- Table with hoverable rows -->
					<table class="table table-hover">
						<tbody>
							@if (Model.PageCount > 1)
							{
								<tr>
									<td>
										@if (Model.CurrentPage != 1)
										{
											<a class="btn btn-secondary" asp-route-query="@Model.Query" asp-page="/Category" asp-route-pageno="@(Model.CurrentPage - 1)">Prev</a>
										}
									</td>
									<td colspan="2">
										@for (int i = Model.CurrentPage; i <= Model.CurrentPage + 5; i++)
										{
											<a class="btn btn-secondary" asp-route-query="@Model.Query" asp-page="/Category" asp-route-pageno="@i">@i</a>
										}
									</td>
									<td>
										<a class="btn btn-secondary" asp-route-query="@Model.Query" asp-page="/Category" asp-route-pageno="@(Model.CurrentPage + 1)">Next</a>
									</td>
								</tr>
							}
						</tbody>
					</table>
						</div>
						<!-- /store bottom filter -->
					</div>
					<!-- /STORE -->
				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
		<!-- /SECTION -->

ECommerceSite/Pages/Checkout.cshtml
@page
@model ECommerceSite.Pages.CheckoutModel
@{
}

ECommerceSite/Pages/Confirmation.cshtml
@page
@model ECommerceSite.Pages.ConfirmationModel
@{
}
<!-- BREADCRUMB -->
<div id="breadcrumb" class="section">
	<!-- container -->
	<div class="container">
		<!-- row -->
		<div class="row">
			<div class="col-md-12">
				<h3 class="breadcrumb-header">Confirmation</h3>
				<ul class="breadcrumb-tree">
				</ul>
			</div>
		</div>
		<!-- /row -->
	</div>
	<!-- /container -->
</div>
<!-- /BREADCRUMB -->
<!-- SECTION -->
<div class="section">
	<!-- container -->
	<div class="container">
		<!-- row -->
		<div class="row">
			<h1>Thanks for your purchase!</h1>
			<h3>A Order receipt has been sent to your email.</h3>
		</div>
		<br />
		<br />
		<div class="row">
			<h5>Please consider signing up for our newsletter down below, we promise not to spam you!</h5>
		</div>
		<!-- /row -->
	</div>
	<!-- /container -->
</div>
<!-- /SECTION -->
<!-- NEWSLETTER -->
<div id="newsletter" class="section">
	<!-- container -->
	<div class="container">
		<!-- row -->
		<div class="row">
			<div class="col-md-12">
				<div class="newsletter">
					<p>Sign Up for the <strong>NEWSLETTER</strong></p>
					<form>
						<input class="input" type="email" placeholder="Enter Your Email">
						<button class="newsletter-btn"><i class="fa fa-envelope"></i> Subscribe</button>
					</form>
					<ul class="newsletter-follow">
						<li>
							<a href="#"><i class="fa fa-facebook"></i></a>
						</li>
						<li>
							<a href="#"><i class="fa fa-twitter"></i></a>
						</li>
						<li>
							<a href="#"><i class="fa fa-instagram"></i></a>
						</li>
						<li>
							<a href="#"><i class="fa fa-pinterest"></i></a>
						</li>
					</ul>
				</div>
			</div>
		</div>
		<!-- /row -->
	</div>
	<!-- /container -->
</div>
<!-- /NEWSLETTER -->